### ISSUE TITLE
Module fails to import because of missing exports

### ISSUE THREAD

**Issue by yitzikc** [tobes31415/dispose#17]
I'm unable to import the module from Typescript code on both Node 14and 16 on OS/X. It fails with the error:
Running my code with _node_ I get:
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/isac/code/TripService/node_modules/@tobes31415/dispose/package.json`

This is reproducible with both Node 14.19.3 with NPM 6.14.17 and Node 16.15 and NPM 8, both when running the _js_ file with node, and when using _ts-node_. Apparently the imports do work when running tests from _jest_.

My _tsconfig.json_ specifies:

`"compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["es2020", "DOM"],
    "esModuleInterop": true,
    "declaration": false,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "typeRoots": ["./node_modules/@types"]
  },` 

The generated _js_ code seems straightforward:

`const dispose_1 = require("@tobes31415/dispose");`

The import also fails when running this line in node REPL interactively.

**Comment by tobes31415** [comment]
I'll check it out.  Which version of dispose are you running?

**Comment by yitzikc** [comment]
The latest - 4.0.4. I also tried downgrading to 4.0.1 which seemed to work fine previously and the problem seems to persist.
PS - Probably the simplest way to reproduce my environment is to install Node 14.19.3 using NVM.

**Comment by tobes31415** [comment]
I'm running with Node 14.19.3 and npm version 6.14.17, using your tsconfig building a plain typescript project, I am running on windows though
```
// main.ts
import {dispose, onDispose} from "@tobes31415/dispose";
const test = {};
onDispose(test, () => console.log("Foo"));
dispose(test);
```
Results in the following output
```
// main.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const dispose_1 = require("@tobes31415/dispose");
const test = {};
(0, dispose_1.onDispose)(test, () => console.log("Foo"));
(0, dispose_1.dispose)(test);
//# sourceMappingURL= ...
```
I'm not getting any error messages when I run the build command.

**Comment by yitzikc** [comment]
The build runs with no errors for me too. However, when I try to run the resulting _js_ file - which would be either `node main.js` or `npx ts-node main.ts` - I get the error described above. Does it run properly for you? If so, could you please share it (including the _js_ file to a repository I can clone and compare the result?

**Comment by tobes31415** [comment]
Oooh there we go.  Reproducing the error now.

**Comment by tobes31415** [comment]
k, I'm assuming this might be blocking you so here is a workaround.  Go into your node_modules folder in the package.json for dispose change the exports line to this
```
  "exports": "./lib/gc-commonjs.min.js",
```
That should unblock you at least temporarily.  I will update the package in a bit, I just need to make sure that change doesn't break something else.  

I am curiously though, why common js?  I've actually been strongly considering to remove common js support and move exclusively to the new module format.

**Comment by tobes31415** [comment]
Actually even just deleting the exports line seems to work too, as it already has the other commonjs fallback.  yeah, remove it instead :-)

**Comment by yitzikc** [comment]
Thanks! I'll wait for the fix in NPM as the build has to run in a scripted environment.
As for using common JS, I did try setting `"module": "es2020"`, and unfortunately that breaks:
https://www.npmjs.com/package/conditional-type-checks

**Comment by tobes31415** [comment]
I've pushed 4.0.5 to npm.  
What was the link?  You pasted conditional type checks, was supposed to be something else?

**Comment by yitzikc** [comment]
The link was for an unrelated library - [conditional-type-checks](https://www.npmjs.com/package/conditional-type-checks) - which causes the build to fail when setting _module_ to newer than CommonJS. Quite annoying, as that one is TS compile-time only and doesn't generate any JS code :-(

**Comment by yitzikc** [comment]
Thanks for the very rapid resolution, much appreciated!
